# Generated by Django 5.1 on 2024-12-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='book_reviews', to='review.review'),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='books', to='book.category'),
        ),
    ]
