# Generated by Django 5.1.4 on 2024-12-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
